### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by SAH01-sys** [VinAIResearch/DSW#2]
Thank you for sharing the codes of this interesting tool. 
I get the error below when running the code in Jupyter. However, this error does not appear when running on google colab.   
I created a new enviornment with Python 3.8.10 and installed _torch==1.4.0 torchvision==0.5.0 numpy tqdm POT scikit-image_.
Any tips to tackle this error please? :)
`run mnist.py --datadir=./ --outdir=./result --batch-size=1 --seed=16 --p=2 --lr=0.05 --dataset=MNIST --model-type=DSWD --latent-size=32 --num-workers=0
`
```
RuntimeError                              Traceback (most recent call last)
~\Sliced Gan\DSW-master\DSW-master\mnist.py in <module>
    327 
    328 if __name__ == "__main__":
--> 329     main()

~\Sliced Gan\DSW-master\DSW-master\mnist.py in main()
    281                     fake = model.decoder(fixednoise_wd)
    282                     wd_list.append(compute_true_Wasserstein(data.to("cpu"), fake.to("cpu")))
--> 283                     swd_list.append(sliced_wasserstein_distance(data, fake, 10000).item())
    284                     print("Iter:" + str(ite) + " WD: " + str(wd_list[-1]))
    285                     np.savetxt(model_dir + "/wd.csv", wd_list, delimiter=",")

~\Sliced Gan\DSW-master\DSW-master\utils.py in sliced_wasserstein_distance(first_samples, second_samples, num_projections, p, device)
     17     wasserstein_distance = torch.abs(
     18         (
---> 19             torch.sort(first_projections.transpose(0, 1), dim=1)[0]
     20             - torch.sort(second_projections.transpose(0, 1), dim=1)[0]
     21         )

RuntimeError: CUDA out of memory. Tried to allocate 1.49 GiB (GPU 0; 4.00 GiB total capacity; 2.00 GiB already allocated; 935.90 MiB free; 2.02 GiB reserved in total by PyTorch)
```

**Comment by khainb** [comment]
Thank you for the question. Please comment the line 283 "swd_list.append(sliced_wasserstein_distance(data, fake, 10000).item())" because it is just for evaluation purposes. Feel free to ask other questions.

**Comment by SAH01-sys** [comment]
Thanks, the issue is solved :)
